[package]
name = "porters"
version = "0.0.0"
authors = ["muhammad-fiaz <contact@muhammadfiaz.com>"]
edition = "2021"

[dependencies]
colored = "3.0"
build_system = { path = "packages/build_system" }
init = { path = "packages/init" }

[[bin]]
name = "porters"
path = "src/main.rs"
