[package]
name = "build_system"
version = "0.1.0"
edition = "2021"

[dependencies]
colored = "3.0"
dialoguer = "0.11"
indicatif = "0.17"
toml = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0"
serde_json = "1.0"


[lib]
path = "src/mod.rs"